#!/bin/bash
# My first script

number=1
max=3
url="http://assets22.pokemon.com/assets/cms2/img/pokedex/full/"
while [ $number -lt 719 ]; do
    numstring=$(printf "%03d" $number)
    echo "$url$numstring.png"
    curl -o "$numstring.png" "$url$numstring.png"
    number=$((number + 1))
done
